### ISSUE TITLE
Open to collaborate and join the capacitor-community?

### ISSUE THREAD

**Issue by mhartington** [capacitor-community/vue-cli-plugin-capacitor#12]
Hey there! I'm making from the Ionic team! It's great to see there's already a Vue CLI plugin for capacitor. Great work on this.

We've recently launched a community org here on github for capacitor that includes various plugins and I was thinking this would be a good candidate for joining the community.

The TL;DR is you'd join the org as a member and would maintain the plugin under that org. That means transferring this repo to a new org with you as the primary maintainer. You would then be able to republish the CLI add on under the npm scope `@capacitor-community`

You can take a look at the community org here 

https://github.com/capacitor-community

Feel free to reach out if you have any other questions!

**Comment by nklayman** [comment]
Thanks for reaching out! I'd love to transfer it over to an official community org, just let me know what to do. I can commit to maintaining it for a while as well.

Ideally, I'd like to publish it under `vue-cli-plugin-capacitor`, so `vue add capacitor` will install it. Unfortunately, the name is held by [this repo](https://github.com/techiediaries/vue-cli-plugin-capacitor). I asked the maintainer if they'd be willing to hand over the name as my plugin is more advanced and uses the latest capacitor version, but they didn't respond (see https://github.com/techiediaries/vue-cli-plugin-capacitor/issues/1). Maybe if they were contacted by an Ionic team member they'd be more likely to respond and give up the name. If not, we can move it under the `@capacitor-community` npm scope instead.

**Comment by mhartington** [comment]
Ok, so I'll start by inviting you to the org and we can begin to transfer the plugin over. 


As for the plugin name/package name, that may be less important. Since it will be under the community package scope on npm, it will need to be something different

**Comment by nklayman** [comment]
I accepted the org invite, should I transfer the repo now?

**Comment by mhartington** [comment]
Sure, transfer it over and we'll go from there. Also, are you in the capacitor slack? If not, can you join here and ping me? We have a private contributors chat that we use to coordinate things


https://getcapacitor.herokuapp.com

**Comment by nklayman** [comment]
I just joined the Slack and pinged you
