### ISSUE TITLE
npm capacitor:serve --ios not honored

### ISSUE THREAD

**Issue by AlanGreyjoy** [capacitor-community/vue-cli-plugin-capacitor#13]
When using the command
npm capacitor:serve --ios
It still only opens android and not xcode.

Any ideas?

**Comment by nklayman** [comment]
With [npm scripts](https://docs.npmjs.com/cli/run-script#description), you need a `--` between script args and npm args. Try `npm run capacitor:serve -- --ios`.

**Comment by AlanGreyjoy** [comment]
oh my...

Thanks for that!
