### ISSUE TITLE
Update documentation for existing capacitor setup

### ISSUE THREAD

**Issue by npostulart** [capacitor-community/vue-cli-plugin-capacitor#15]
**Is your feature request related to a problem? Please describe.**
Using `vue add capacitor` on a project already setup with capacitor the installation fails.

**Describe the solution you'd like**
Installation instructions for installing the cli plugin on an existing Vue / Capacitor setup.

**Comment by nklayman** [comment]
What happens if you don't select any platforms during installation? I think it will work then.

**Comment by npostulart** [comment]
It's not possible to continue the install process if no target platform is selected.

**Comment by nklayman** [comment]
Oh yeah, my bad 🤦‍♂️. It seems like a pretty uncommon use case, but you can just rename the folder, invoke the plugin, then delete the new folder and replace with the old one.

**Comment by alexwohlbruck** [comment]
> Oh yeah, my bad 🤦‍♂️. It seems like a pretty uncommon use case, but you can just rename the folder, invoke the plugin, then delete the new folder and replace with the old one.

Can you elaborate on this? What folder do you mean?
