### ISSUE TITLE
How  to print document?

### ISSUE THREAD

**Issue by ibalaji777** [capacitor-community/vue-cli-plugin-capacitor#19]
I need to print html content but I can't  see any document relative to print. I have seen cordova-plugin-printer  how to configure inside capacitor?

**Comment by nklayman** [comment]
You should check the [capacitor docs](https://capacitorjs.com/docs) for instructions. This plugin just sets up capacitor, and doesn't have anything to do with plugin usage. If you run into errors you should ask for help in the [capacitor forum](https://forum.ionicframework.com/c/capacitor/).
