### ISSUE TITLE
Errors with plugins. All of them.

### ISSUE THREAD

**Issue by AlanGreyjoy** [capacitor-community/vue-cli-plugin-capacitor#23]
While this may not be a bug, but I have no one else to ask.

I get this error anytime I use a plugin.
![image](https://user-images.githubusercontent.com/4026982/124360178-08b96800-dbee-11eb-9ab6-ca87592f79f0.png)

I also get this error on some plugins.
![image](https://user-images.githubusercontent.com/4026982/124360334-d2c8b380-dbee-11eb-94c2-3004655f2c01.png)

This is during npm run capacitor:serve -- --android
and also running directly on a device, not an emulator

Any help is greatly appreciated!

**Comment by ibalaji777** [comment]
```
npm install   --save-dev jetifier
npx jetify
npx cap sync 
run npm run capacitor:serve
```

**Comment by AlanGreyjoy** [comment]
So, it turns out, I had @capacitor/android 3 and @capacitor/core 2
I downgraded android to 2.something and its all good now.
